#ifndef HEADER_H_INCLUDED
    #define HEADER_H_INCLUDED

#define KEY_LENGTH 32
#define NONCE_LENGTH 24
#define HOST_LENGTH 6

#define STATE_LENGTH (KEY_LENGTH+NONCE_LENGTH+HOST_LENGTH)

#define CIPHER_HEADER_LENGTH (16+NONCE_LENGTH)

#define STATE1_A_LENGTH (KEY_LENGTH+HOST_LENGTH+NONCE_LENGTH)
#define STATE2_A_LENGTH KEY_LENGTH
#define STATE_B_LENGTH (KEY_LENGTH+NONCE_LENGTH)

#define MESSAGE1_LENGTH (HOST_LENGTH+HOST_LENGTH+NONCE_LENGTH)
#define MESSAGE3_LENGTH (CIPHER_HEADER_LENGTH+KEY_LENGTH+HOST_LENGTH)
#define MESSAGE2_LENGTH (CIPHER_HEADER_LENGTH+NONCE_LENGTH+KEY_LENGTH+HOST_LENGTH+MESSAGE3_LENGTH)
#define MESSAGE4_LENGTH (CIPHER_HEADER_LENGTH+NONCE_LENGTH)
#define MESSAGE5_LENGTH (CIPHER_HEADER_LENGTH+NONCE_LENGTH)

#endif // HEADER_H_INCLUDED
